<a href="https://colab.research.google.com/github/Shoylekov/Machine-Learning-Projects/blob/main/ChurnPred.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from imblearn.combine import SMOTEENN
from sklearn.preprocessing import LabelEncoder

In [ ]:
from google.colab import files
upload = files.upload()

Saving WA_Fn-UseC_-Telco-Customer-Churn.csv to WA_Fn-UseC_-Telco-Customer-Churn (1).csv


In [ ]:
df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [ ]:
df.head(5)

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [ ]:
df = df.drop('customerID', axis=1)

In [ ]:
for column in df.columns:
  if df[column].dtype == np.number:
    continue
  df[column] = LabelEncoder().fit_transform(df[column])

<ipython-input-37-27244ba8230d>:2: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  if df[column].dtype == np.number:
<ipython-input-37-27244ba8230d>:2: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  if df[column].dtype == np.number:
<ipython-input-37-27244ba8230d>:2: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  if df[column].dtype == np.number:
<ipython-input-37-27244ba8230d>:2: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  if df[column].dtype == np.number:
<ipython-input-37-27244ba8230d>:2: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprec

In [ ]:
x = df.drop('Churn', axis=1)
x

gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0          0              0        1           0       1             0   
1          1              0        0           0      34             1   
2          1              0        0           0       2             1   
3          1              0        0           0      45             0   
4          0              0        0           0       2             1   
...      ...            ...      ...         ...     ...           ...   
7038       1              0        1           1      24             1   
7039       0              0        1           1      72             1   
7040       0              0        1           1      11             0   
7041       1              1        1           0       4             1   
7042       1              0        0           0      66             1   

      MultipleLines  InternetService  OnlineSecurity  OnlineBackup  \
0                 1                0               0             2   
1                 0                0               2             0   
2                 0                0               2             2   
3                 1                0               2             0   
4                 0                1               0             0   
...             ...              ...             ...           ...   
7038              2                0               2             0   
7039              2                1               0             2   
7040              1                0               2             0   
7041              2                1               0             0   
7042              0                1               2             0   

      DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
0                    0            0            0                0         0   
1                    2            0            0                0         1   
2                    0            0            0                0         0   
3                    2            2            0                0         1   
4                    0            0            0                0         0   
...                ...          ...          ...              ...       ...   
7038                 2            2            2                2         1   
7039                 2            0            2                2         1   
7040                 0            0            0                0         0   
7041                 0            0            0                0         0   
7042                 2            2            2                2         2   

      PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges  
0                    1              2           29.85          2505  
1                    0              3           56.95          1466  
2                    1              3           53.85           157  
3                    0              0           42.30          1400  
4                    1              2           70.70           925  
...                ...            ...             ...           ...  
7038                 1              3           84.80          1597  
7039                 1              1          103.20          5698  
7040                 1              2           29.60          2994  
7041                 1              3           74.40          2660  
7042                 1              0          105.65          5407  

[7043 rows x 19 columns]

In [ ]:
y = df['Churn']
y

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7043, dtype: int64

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [ ]:
model_dt = DecisionTreeClassifier(criterion='gini', random_state = 100, max_depth=6, min_samples_leaf=8)

In [ ]:
model_dt.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [ ]:
y_pred = model_dt.predict(x_test)

In [ ]:
y_pred

array([0, 0, 0, ..., 0, 1, 0])

In [ ]:
model_dt.score(x_test, y_pred)

1.0

In [ ]:
print(classification_report(y_test, y_pred, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.82      0.91      0.87      1052
           1       0.62      0.43      0.50       357

    accuracy                           0.79      1409
   macro avg       0.72      0.67      0.69      1409
weighted avg       0.77      0.79      0.77      1409



In [ ]:
print(confusion_matrix(y_test, y_pred))

[[959  93]
 [205 152]]


In [ ]:
sm = SMOTEENN()
X_resampled, y_resampled = sm.fit_resample(x, y)

In [ ]:
xr_train, xr_test, yr_train, yr_test = train_test_split(X_resampled, y_resampled, test_size = 0.2)

In [ ]:
model_dt_smote = DecisionTreeClassifier(criterion='gini', random_state = 100, max_depth=6, min_samples_leaf=8)

In [ ]:
model_dt_smote.fit(xr_train, yr_train)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [ ]:
y_pred_smote = model_dt_smote.predict(xr_test)

In [ ]:
print(classification_report(yr_test, y_pred_smote, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.95      0.87      0.91       535
           1       0.90      0.96      0.93       649

    accuracy                           0.92      1184
   macro avg       0.93      0.92      0.92      1184
weighted avg       0.92      0.92      0.92      1184



In [ ]:
print(confusion_matrix(yr_test, y_pred_smote))

[[465  70]
 [ 24 625]]


In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
model_rf = RandomForestClassifier(n_estimators=100, criterion='gini', random_state=100, max_depth=6, min_samples_leaf=8)
model_rf.fit(x_train, y_train)
y_pred_rf = model_rf.predict(x_test)

In [ ]:
print(classification_report(y_test, y_pred_rf, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.83      0.92      0.87      1052
           1       0.65      0.45      0.53       357

    accuracy                           0.80      1409
   macro avg       0.74      0.68      0.70      1409
weighted avg       0.78      0.80      0.79      1409



In [ ]:
sm = SMOTEENN()
X_resampled, y_resampled = sm.fit_resample(x, y)

In [ ]:
xr_train, xr_test, yr_train, yr_test = train_test_split(X_resampled, y_resampled, test_size = 0.2)

In [ ]:
model_smote_rf = RandomForestClassifier(criterion='gini', random_state = 100, max_depth=6, min_samples_leaf=8)

In [ ]:
model_smote_rf.fit(xr_train, yr_train)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [ ]:
y_pred_smote_rf = model_smote_rf.predict(xr_test)

In [ ]:
print(classification_report(yr_test, y_pred_smote_rf, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.95      0.89      0.92       566
           1       0.91      0.95      0.93       620

    accuracy                           0.92      1186
   macro avg       0.93      0.92      0.92      1186
weighted avg       0.92      0.92      0.92      1186



In [ ]:
import pickle

In [ ]:
 filename = 'model.sav'

In [ ]:
pickle.dump(model_smote_rf, open(filename, 'wb'))

In [ ]:
load_model = pickle.load(open(filename, 'rb'))

In [ ]:
load_model.score(xr_test, yr_test)

0.9232715008431703

In [ ]:
import sklearn
print(sklearn.__version__)

1.2.2
